### ISSUE TITLE
Version revert (ncloud-sdk-go-v2@v1.2.0) causing issues with golang proxies

### ISSUE THREAD

**Issue by haata** [hashicorp/packer-plugin-ncloud#12] opened 2021-08-27 18:14 UTC
https://github.com/hashicorp/packer-plugin-ncloud/commit/745e8153c33676dc63ee8089c534c44ab8d85f82#diff-33ef32bf6c23acb95f5902d7097b7a1d5128ca061167ec0716715b0b9eeaa5f6
Rollback causing issues with athens proxy server.

sum.golang.org does not revert pulled packages which means that if you use the athens proxy you'll get this

```
go: downloading github.com/hashicorp/packer v1.7.4
go get: github.com/hashicorp/packer@v1.7.4 requires
	github.com/hashicorp/packer-plugin-ncloud@v1.0.0 requires
	github.com/NaverCloudPlatform/ncloud-sdk-go-v2@v1.2.0: reading https://****/github.com/%21naver%21cloud%21platform/ncloud-sdk-go-v2/@v/v1.2.0.mod: 404 Not Found
```

As per https://sum.golang.org/, please push new releases of packer-plugin-ncloud and packer

> I removed a bad release from my repository but it still appears in the mirror, what should I do?
>
> Whenever possible, the mirror aims to cache content in order to avoid breaking builds for people that depend on your package,  so this bad release may still be available in the mirror even if it is not available at the origin. The same situation applies if you delete your entire repository. We suggest creating a new version and encouraging people to use that one instead.

**Comment by nywilken** [comment] 2022-06-10 17:46
I believe this is no longer an issue since ncloud and Packer have been released multiple times since this issue. I'm going to to close this issue. If this is still a bug please provide details steps for reproducing this issue including the version of Packer being built, and the version of Go being used.

**Closed by nywilken** 2022-06-10 17:46 UTC
Labels: bug
